[project]
name = "django-form2model"
version = "0.1.0"
description = "Pomocnicze funkcje do Django"
readme = "README.md"
license = {text = "MIT"}
dependencies = ["Django>=3.2"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
